kind: pipeline
name: default

steps:
- name: build
  image: golang
  commands:
  - go test
  - go build
  - go run main.go
  - ls -l
  # no idea why this is necessary, but when running in place (on tmpfs)...
  #   + ./drone-example
  #   /usr/drone/bin/init: 35: /usr/drone/bin/init: ./drone-example: Permission denied
  - cp -a ./drone-example /tmp
  - /tmp/drone-example
