kind: pipeline
name: default

steps:
- name: build
  image: golang
  commands:
  - go test
  - go build

- name: run
  image: debian:stretch
  commands:
  - ls -l
  - pwd
  - file ./drone-example
  - ./drone-example
