kind: pipeline
name: default

steps:
- name: build
  image: golang
  commands:
  - go test
  - go build

- name: run
  image: debian:stretch
  commands:
  - apt-get update && apt-get install file -y
  - ls -l
  - pwd
  - whoami
  - file ./drone-example
  - ./drone-example
